In [13]:
import torch
batch_size = 2
seq_len = 3
input_size = 4
hidden_size = 2

In [14]:
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)

In [15]:
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)
print(dataset)
print('-' * 20)
print(hidden)
for idx, input in enumerate(dataset):
    print('='*20,idx,'='*20)
    print('Input size:',input.shape)
    hidden = cell(input, hidden)
    print('outputs size:',hidden.shape)
    print(hidden)

tensor([[[-0.9765, -0.1460,  0.1503, -0.1829],
         [ 2.5885,  0.8175,  0.0160, -0.3044]],

        [[ 0.6212,  0.1999,  0.9007, -1.2547],
         [ 0.7534, -1.8983,  1.0359,  0.1173]],

        [[ 0.2075, -1.0992,  0.0957, -0.1829],
         [-0.8546, -0.3905,  1.6016, -0.0211]]])
--------------------
tensor([[0., 0.],
        [0., 0.]])
==================== 0 ====================
Input size: torch.Size([2, 4])
outputs size: torch.Size([2, 2])
tensor([[ 0.7288,  0.2259],
        [-0.0258,  0.9656]], grad_fn=<TanhBackward0>)
==================== 1 ====================
Input size: torch.Size([2, 4])
outputs size: torch.Size([2, 2])
tensor([[ 0.7403, -0.0714],
        [ 0.3733, -0.4918]], grad_fn=<TanhBackward0>)
==================== 2 ====================
Input size: torch.Size([2, 4])
outputs size: torch.Size([2, 2])
tensor([[ 0.7130, -0.3286],
        [ 0.9458,  0.1113]], grad_fn=<TanhBackward0>)
